import Head from 'next/head'
import Image from 'next/image'
import { Poppins } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import React from 'react'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'


const poppins = Poppins({ subsets: ['latin'], weight: ["100","200","300"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Janki Bariya | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      
    </>
  )
}
